# Generated by Django 5.0.14 on 2026-07-15 14:40

import django.db.models.deletion
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags, e.g. django, tutorial, python', max_length=255)),
                ('video_file', models.FileField(upload_to=videos.models.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=videos.models.thumbnail_upload_path)),
                ('hls_playlist', models.FileField(blank=True, help_text='Master HLS playlist path when adaptive streaming is available.', null=True, upload_to=videos.models.hls_upload_path)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds.')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='Bytes.')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('published', 'Published'), ('draft', 'Draft')], default='processing', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='categories.category')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('violence', 'Violent or repulsive'), ('hate', 'Hateful or abusive'), ('sexual', 'Sexual content'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Report',
                'verbose_name_plural': 'Video Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['slug'], name='videos_vide_slug_92e2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', '-created_at'], name='videos_vide_status_9ed8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-view_count'], name='videos_vide_view_co_02bc14_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-like_count'], name='videos_vide_like_co_f8ad1d_idx'),
        ),
    ]
